feat(page): develop-recruitment-page
hanowwl/recruit.hanowl.com pull request #12
Opened 2023-03-06 07:15 UTC by choi138

## 🔍 What is this PR?
- 이슈 넘버: #7 

## 📸 스크린 샷
**어떤 점이 달라졌는지 알 수 있게끔 스크린 샷을 첨부해주세요.**

## ✅ 체크 리스트
- [ ]  **테스트 계획 또는 완료된 사항의 체크리스트를 작성해주세요.**

2023-03-06 09:46 UTC, cmg8431 requested changes

2023-03-06 09:46 UTC, cmg8431 commented on src/pages/teams/index.tsx
> +import { FieldIntroduce } from '../../components/field-introduce';
절대 경로 셋업 후 사용해주면 좋을 것 같아요, 그리고 export를 통해 임폴트 시 뎁스를 줄일 수 있으니 한번 확인 부탁드려요 :)

예:) `import { FieldIntroduce } from '@/components';`

2023-03-06 09:46 UTC, cmg8431 commented on src/pages/teams/index.tsx
> +} from '../../constant';
마찬가지로 절대 경로 지정하는게 좋을 것 같습니다!

2023-03-06 09:46 UTC, cmg8431 commented on src/pages/teams/index.tsx
> +  const field: { title: string; id: string }[] = [
해당 정보는 변하지 않는 값이라 constants에 선언해두는게 좋을 것 같네요

2023-03-06 09:46 UTC, cmg8431 commented on src/pages/teams/index.tsx
> +      {myQueryParam === 'develop' ? (
해당 구조는 그렇게 효율적인 것 같지 않아요! 한번에 데이터를 처리할 수 있을 것 같은데 해당 부분은 같이 이야기해보면 좋을 것 같습니다.

2023-03-06 09:49 UTC, cmg8431 reviewed
@hanseo0507 
develop 브랜치의 경우 Approve 없이 머지가 가능하게 설정되어 있어, 오가니제이션 관련 세팅 후 막아 두었습니다

2023-03-06 09:51 UTC, cmg8431 commented on src/pages/teams/index.tsx
> +      {myQueryParam === 'develop' ? (
@hanseo0507 @choi138 
해당 구조에 대해서는 오늘 저녁에 한번 이야기 하면 좋을 것 같은데 시간 괜찮으실까요? 8시 30분에서 9시쯤이 좋을 것 같습니다!

2023-03-06 09:52 UTC, choi138 commented on src/pages/teams/index.tsx
> +      {myQueryParam === 'develop' ? (
네! 그때 시간 괜찮습니다

2023-03-06 09:56 UTC, cmg8431 commented on src/components/field-introduce/index.tsx
> +  }[];
해당 타입의 경우 IntroductionType을 선언 후 할당해주는게 어떨까요?

예)
```typescript
type IntroductionType = {
   wantedPerson: string;
   haveExperience: string;
}

interface FieldIntroduceProps {
  title: string;
  description: string;
  description2: string;
  introduction: IntroductionType[]
 }

```

2023-03-06 10:07 UTC, hanseo0507 requested changes
코멘드 남겨드린 내용들 확인 후 수정해주시고, 그리고 스타일 코드들 보면 단위로 `px` 사용 중이신데, `rem` 단위로 변경 필요해요.

이 부분은 이따 저녁에 같이 진행하면 좋을 것 같네요.

2023-03-06 10:07 UTC, hanseo0507 commented on src/components/field-introduce/index.tsx
> +  }[];
예시 페이지의 데이터를 이렇게 구조화하신 것 같은데, 해당 데이터는 각 부서별로 내용이 많이 달라질 수 있어요.
좀 더 커스터마이징이 간편한 데이터 구조를 다시 생각해보는 게 좋을 거 같아요.

2023-03-06 10:07 UTC, hanseo0507 commented on src/components/field-introduce/styled.ts
> +  /* border: 1px solid white; */
주석 처리된 코드는 제거해주세요

2023-03-06 10:07 UTC, hanseo0507 commented on src/pages/teams/index.tsx
> +} from '../../constant';
`FieldIntroduceProps`의 Key를 분리해서 모두 import 한 것같은데, 하나로 묶을 수 있는 데이터들을 분리해서 import 하는 건 불필요한 코드가 너무 많아져요. 아래처럼 하나의 Object로 묶는 게 좋을 것 같아요.

```ts
const DEVELOP_INTRODUCE: FieldIntroduceProps = {
// fill
}
```

2023-03-06 10:07 UTC, hanseo0507 commented on src/pages/teams/index.tsx
> +  const myQueryParam = searchParams.get('active');
해당 변수명만 봤을 땐, 이 변수가 정확히 어떤 데이터를 가지고 있는 변수인지 잘 모르겠어요.
변수명을 다시 생각해보는 게 좋을 거 같네요.

2023-03-06 10:07 UTC, hanseo0507 commented on src/pages/teams/index.tsx
> +      {myQueryParam === 'develop' ? (
저도 같은 생각입니다 :)

2023-03-06 10:07 UTC, hanseo0507 commented on src/App.tsx
> +import { TeamPage } from './pages/teams';
`src/pages` 내에 `index.ts` 파일을 추가해서 페이지들을 모두 export 하고, 아래 코드처럼 import 할 수 있도록 수정해주세요.

```ts
import { MainPage, TeamPage } from "./pages";
```

2023-03-06 10:08 UTC, hanseo0507 commented on src/pages/teams/index.tsx
> +      {myQueryParam === 'develop' ? (
@cmg8431 저는 9시 ~ 9시 30분 쯤 가능할 거 같아요 (🏢)

2023-03-06 10:11 UTC, cmg8431 commented on src/pages/teams/index.tsx
> +  const myQueryParam = searchParams.get('active');
그리고 Param의 이름도 `active` 말고 다른 명칭을 사용하는게 더 이해하기 쉬울 것 같습니다! 
예를 들어 해당 Param에 어떤 정보가 들어오는지 고민해보면 좋을 것 같아요!

2023-03-06 10:13 UTC, cmg8431 commented on src/pages/teams/index.tsx
> +      {myQueryParam === 'develop' ? (
확인했습니다! 그럼 9시쯤 디스코드에서 보는 걸로 할게요!

2023-03-06 15:36 UTC, hanseo0507 requested changes

2023-03-06 15:36 UTC, hanseo0507 commented on src/components/FieldIntroduce/styled.ts
> +  > section:nth-of-type(2) {
앞에 `&` 넣어주세요

2023-03-06 15:36 UTC, hanseo0507 commented on src/components/FieldIntroduce/styled.ts
> +    /* border: 1px solid red; */
사용하지 않는 스타일 코드 제거해주세요

2023-03-06 15:36 UTC, hanseo0507 commented on src/constant/teams.ts
> +}
이거 필요 없는 함수라서, 제거해주시면 될 거 같습니다 :)

2023-03-06 15:36 UTC, hanseo0507 commented on src/components/FieldIntroduce/index.tsx
> +export const FieldIntroduce: React.FC<FieldIntroduceProps> = ({ sections }) => {
좀 더 직관적인 이름으로 컴포넌트명을 수정해주세요.
그리고 사용하지 않는 타입/코드도 함께 제거해주세요

2023-03-07 02:03 UTC, hanseo0507 commented
`develop-teams` 커밋 스코프 rebase 수정 완료

2023-03-07 02:16 UTC, hanseo0507 approved these changes, later dismissed

2023-03-07 02:20 UTC, merged